### ISSUE TITLE
pixelData is 2x what you get from dicom?

### ISSUE THREAD

**Issue by blazespinnaker** [tsangel/dicomsdl#1]
```
st = time.time()
pa = dset.pixelData()
print(time.time() - st, pa.nbytes)
st = time.time()
image_dataset = dcmread(f).pixel_array
print(time.time() - st, image_dataset.nbytes*2)
```

1.2884056568145752 105279300
1.5564007759094238 105279300

Faster too.. nice!

**Comment by tsangel** [comment]
pydicom’s pixel_array returns ‘stored value’ in DICOM file in array with some integer type.
DICOMSDL’s pixelData() returns ‘float32’ array, which contains value after ‘rescaling’ or ‘windowing’ operation.
So, its normal that pixelData array size is 2x than pydicom’s pixel_array.

> pa = dset.pixelData()   # DICOMSDL

is similar to

> dset = dcmread(f)  # pydicom
> pa = apply_voi_lut(dset.pixel_array, dset) 



> pa_storedvalue = dcmread(f).pixel_array # pydicom

is similar to

> import dicomsdl as dicom  # DICOMSDL
> pa_storedvalue  = dicom.open(filename).pixelData(storedvalue=True)

You can pick just ‘stored value’ in integer format ‘storedvalue=True’ option
